// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUSq3yGg4IFaVz6_H84r_zSPqtnTs-I6I',
    appId: '1:485279782576:android:0b0f9884e11790dc85cd75',
    messagingSenderId: '485279782576',
    projectId: 'cashvan-25d98',
    storageBucket: 'cashvan-25d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJeAmuqLKJYOkFzVmMWPzzz8PWOHbrGI',
    appId: '1:485279782576:ios:b5ec868037ad801f85cd75',
    messagingSenderId: '485279782576',
    projectId: 'cashvan-25d98',
    storageBucket: 'cashvan-25d98.appspot.com',
    iosClientId:
        '485279782576-r70deunrkad1r9frce08n0iu7k7fvpj3.apps.googleusercontent.com',
    iosBundleId: 'com.aqlaan.amal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxJeAmuqLKJYOkFzVmMWPzzz8PWOHbrGI',
    appId: '1:485279782576:ios:65753117be17793985cd75',
    messagingSenderId: '485279782576',
    projectId: 'cashvan-25d98',
    storageBucket: 'cashvan-25d98.appspot.com',
    iosClientId:
        '485279782576-brve2nbuiiuuvf1li8hbo28afsp1q1vr.apps.googleusercontent.com',
    iosBundleId: 'com.aqlaan.amal',
  );
}
